//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Generaciya_6
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Анкетирование.
    /// </summary>
    // *** Start programmer edit section *** (Анкетирование CustomAttributes)

    // *** End programmer edit section *** (Анкетирование CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("АнкетированиеE", new string[] {
            "Дата as \'Дата\'",
            "Опрос as \'Опрос\'",
            "Опрос.название as \'Название\'"}, Hidden=new string[] {
            "Опрос.название"})]
    [MasterViewDefineAttribute("АнкетированиеE", "Опрос", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "название")]
    public class Анкетирование : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.Generaciya_6.Опрос fОпрос;
        
        private IIS.Generaciya_6.Список fСписок;
        
        // *** Start programmer edit section *** (Анкетирование CustomMembers)

        // *** End programmer edit section *** (Анкетирование CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Анкетирование.Дата CustomAttributes)

        // *** End programmer edit section *** (Анкетирование.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Анкетирование.Дата Get start)

                // *** End programmer edit section *** (Анкетирование.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Анкетирование.Дата Get end)

                // *** End programmer edit section *** (Анкетирование.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкетирование.Дата Set start)

                // *** End programmer edit section *** (Анкетирование.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Анкетирование.Дата Set end)

                // *** End programmer edit section *** (Анкетирование.Дата Set end)
            }
        }
        
        /// <summary>
        /// Анкетирование.
        /// </summary>
        // *** Start programmer edit section *** (Анкетирование.Опрос CustomAttributes)

        // *** End programmer edit section *** (Анкетирование.Опрос CustomAttributes)
        [PropertyStorage(new string[] {
                "Опрос"})]
        [NotNull()]
        public virtual IIS.Generaciya_6.Опрос Опрос
        {
            get
            {
                // *** Start programmer edit section *** (Анкетирование.Опрос Get start)

                // *** End programmer edit section *** (Анкетирование.Опрос Get start)
                IIS.Generaciya_6.Опрос result = this.fОпрос;
                // *** Start programmer edit section *** (Анкетирование.Опрос Get end)

                // *** End programmer edit section *** (Анкетирование.Опрос Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкетирование.Опрос Set start)

                // *** End programmer edit section *** (Анкетирование.Опрос Set start)
                this.fОпрос = value;
                // *** Start programmer edit section *** (Анкетирование.Опрос Set end)

                // *** End programmer edit section *** (Анкетирование.Опрос Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Generaciya_6.Список.
        /// </summary>
        // *** Start programmer edit section *** (Анкетирование.Список CustomAttributes)

        // *** End programmer edit section *** (Анкетирование.Список CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Список"})]
        public virtual IIS.Generaciya_6.Список Список
        {
            get
            {
                // *** Start programmer edit section *** (Анкетирование.Список Get start)

                // *** End programmer edit section *** (Анкетирование.Список Get start)
                IIS.Generaciya_6.Список result = this.fСписок;
                // *** Start programmer edit section *** (Анкетирование.Список Get end)

                // *** End programmer edit section *** (Анкетирование.Список Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкетирование.Список Set start)

                // *** End programmer edit section *** (Анкетирование.Список Set start)
                this.fСписок = value;
                // *** Start programmer edit section *** (Анкетирование.Список Set end)

                // *** End programmer edit section *** (Анкетирование.Список Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "АнкетированиеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АнкетированиеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АнкетированиеE", typeof(IIS.Generaciya_6.Анкетирование));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Анкетирование.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfАнкетирование CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfАнкетирование CustomAttributes)
    public class DetailArrayOfАнкетирование : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Generaciya_6.DetailArrayOfАнкетирование members)

        // *** End programmer edit section *** (IIS.Generaciya_6.DetailArrayOfАнкетирование members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Анкетирование by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Анкетирование.
        /// </summary>
        public DetailArrayOfАнкетирование(IIS.Generaciya_6.Список fСписок) : 
                base(typeof(Анкетирование), ((ICSSoft.STORMNET.DataObject)(fСписок)))
        {
        }
        
        public IIS.Generaciya_6.Анкетирование this[int index]
        {
            get
            {
                return ((IIS.Generaciya_6.Анкетирование)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Generaciya_6.Анкетирование dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
