//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Generaciya_6
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Содержание.
    /// </summary>
    // *** Start programmer edit section *** (содержание CustomAttributes)

    // *** End programmer edit section *** (содержание CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("содержаниеE", new string[] {
            "Вопрос as \'Вопрос\'",
            "В1 as \'В1\'",
            "В2 as \'В2\'",
            "В3 as \'В3\'"})]
    public class содержание : ICSSoft.STORMNET.DataObject
    {
        
        private string fВопрос;
        
        private string fВ1;
        
        private string fВ2;
        
        private string fВ3;
        
        private IIS.Generaciya_6.НастройкаОпр fНастройкаОпр;
        
        // *** Start programmer edit section *** (содержание CustomMembers)

        // *** End programmer edit section *** (содержание CustomMembers)

        
        /// <summary>
        /// В1.
        /// </summary>
        // *** Start programmer edit section *** (содержание.В1 CustomAttributes)

        // *** End programmer edit section *** (содержание.В1 CustomAttributes)
        [StrLen(255)]
        public virtual string В1
        {
            get
            {
                // *** Start programmer edit section *** (содержание.В1 Get start)

                // *** End programmer edit section *** (содержание.В1 Get start)
                string result = this.fВ1;
                // *** Start programmer edit section *** (содержание.В1 Get end)

                // *** End programmer edit section *** (содержание.В1 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (содержание.В1 Set start)

                // *** End programmer edit section *** (содержание.В1 Set start)
                this.fВ1 = value;
                // *** Start programmer edit section *** (содержание.В1 Set end)

                // *** End programmer edit section *** (содержание.В1 Set end)
            }
        }
        
        /// <summary>
        /// В2.
        /// </summary>
        // *** Start programmer edit section *** (содержание.В2 CustomAttributes)

        // *** End programmer edit section *** (содержание.В2 CustomAttributes)
        [StrLen(255)]
        public virtual string В2
        {
            get
            {
                // *** Start programmer edit section *** (содержание.В2 Get start)

                // *** End programmer edit section *** (содержание.В2 Get start)
                string result = this.fВ2;
                // *** Start programmer edit section *** (содержание.В2 Get end)

                // *** End programmer edit section *** (содержание.В2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (содержание.В2 Set start)

                // *** End programmer edit section *** (содержание.В2 Set start)
                this.fВ2 = value;
                // *** Start programmer edit section *** (содержание.В2 Set end)

                // *** End programmer edit section *** (содержание.В2 Set end)
            }
        }
        
        /// <summary>
        /// В3.
        /// </summary>
        // *** Start programmer edit section *** (содержание.В3 CustomAttributes)

        // *** End programmer edit section *** (содержание.В3 CustomAttributes)
        [StrLen(255)]
        public virtual string В3
        {
            get
            {
                // *** Start programmer edit section *** (содержание.В3 Get start)

                // *** End programmer edit section *** (содержание.В3 Get start)
                string result = this.fВ3;
                // *** Start programmer edit section *** (содержание.В3 Get end)

                // *** End programmer edit section *** (содержание.В3 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (содержание.В3 Set start)

                // *** End programmer edit section *** (содержание.В3 Set start)
                this.fВ3 = value;
                // *** Start programmer edit section *** (содержание.В3 Set end)

                // *** End programmer edit section *** (содержание.В3 Set end)
            }
        }
        
        /// <summary>
        /// Вопрос.
        /// </summary>
        // *** Start programmer edit section *** (содержание.Вопрос CustomAttributes)

        // *** End programmer edit section *** (содержание.Вопрос CustomAttributes)
        [StrLen(255)]
        public virtual string Вопрос
        {
            get
            {
                // *** Start programmer edit section *** (содержание.Вопрос Get start)

                // *** End programmer edit section *** (содержание.Вопрос Get start)
                string result = this.fВопрос;
                // *** Start programmer edit section *** (содержание.Вопрос Get end)

                // *** End programmer edit section *** (содержание.Вопрос Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (содержание.Вопрос Set start)

                // *** End programmer edit section *** (содержание.Вопрос Set start)
                this.fВопрос = value;
                // *** Start programmer edit section *** (содержание.Вопрос Set end)

                // *** End programmer edit section *** (содержание.Вопрос Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Generaciya_6.НастройкаОпр.
        /// </summary>
        // *** Start programmer edit section *** (содержание.НастройкаОпр CustomAttributes)

        // *** End programmer edit section *** (содержание.НастройкаОпр CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "НастройкаОпр"})]
        public virtual IIS.Generaciya_6.НастройкаОпр НастройкаОпр
        {
            get
            {
                // *** Start programmer edit section *** (содержание.НастройкаОпр Get start)

                // *** End programmer edit section *** (содержание.НастройкаОпр Get start)
                IIS.Generaciya_6.НастройкаОпр result = this.fНастройкаОпр;
                // *** Start programmer edit section *** (содержание.НастройкаОпр Get end)

                // *** End programmer edit section *** (содержание.НастройкаОпр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (содержание.НастройкаОпр Set start)

                // *** End programmer edit section *** (содержание.НастройкаОпр Set start)
                this.fНастройкаОпр = value;
                // *** Start programmer edit section *** (содержание.НастройкаОпр Set end)

                // *** End programmer edit section *** (содержание.НастройкаОпр Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "содержаниеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View содержаниеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("содержаниеE", typeof(IIS.Generaciya_6.содержание));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of содержание.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfсодержание CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfсодержание CustomAttributes)
    public class DetailArrayOfсодержание : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Generaciya_6.DetailArrayOfсодержание members)

        // *** End programmer edit section *** (IIS.Generaciya_6.DetailArrayOfсодержание members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type содержание by index.
        /// </summary>
        /// <summary>
        /// Adds object with type содержание.
        /// </summary>
        public DetailArrayOfсодержание(IIS.Generaciya_6.НастройкаОпр fНастройкаОпр) : 
                base(typeof(содержание), ((ICSSoft.STORMNET.DataObject)(fНастройкаОпр)))
        {
        }
        
        public IIS.Generaciya_6.содержание this[int index]
        {
            get
            {
                return ((IIS.Generaciya_6.содержание)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Generaciya_6.содержание dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
