//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Generaciya_6
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудники.
    /// </summary>
    // *** Start programmer edit section *** (Сотрудники CustomAttributes)

    // *** End programmer edit section *** (Сотрудники CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотрудникиE", new string[] {
            "имя as \'Имя\'",
            "Список as \'Список\'"})]
    [MasterViewDefineAttribute("СотрудникиE", "Список", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "")]
    [View("СотрудникиL", new string[] {
            "имя as \'Имя\'"})]
    public class Сотрудники : ICSSoft.STORMNET.DataObject
    {
        
        private string fимя;
        
        private IIS.Generaciya_6.Список fСписок;
        
        // *** Start programmer edit section *** (Сотрудники CustomMembers)

        // *** End programmer edit section *** (Сотрудники CustomMembers)

        
        /// <summary>
        /// имя.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.имя CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.имя CustomAttributes)
        [StrLen(255)]
        public virtual string имя
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.имя Get start)

                // *** End programmer edit section *** (Сотрудники.имя Get start)
                string result = this.fимя;
                // *** Start programmer edit section *** (Сотрудники.имя Get end)

                // *** End programmer edit section *** (Сотрудники.имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.имя Set start)

                // *** End programmer edit section *** (Сотрудники.имя Set start)
                this.fимя = value;
                // *** Start programmer edit section *** (Сотрудники.имя Set end)

                // *** End programmer edit section *** (Сотрудники.имя Set end)
            }
        }
        
        /// <summary>
        /// Сотрудники.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Список CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Список CustomAttributes)
        [PropertyStorage(new string[] {
                "Список"})]
        [NotNull()]
        public virtual IIS.Generaciya_6.Список Список
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Список Get start)

                // *** End programmer edit section *** (Сотрудники.Список Get start)
                IIS.Generaciya_6.Список result = this.fСписок;
                // *** Start programmer edit section *** (Сотрудники.Список Get end)

                // *** End programmer edit section *** (Сотрудники.Список Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Список Set start)

                // *** End programmer edit section *** (Сотрудники.Список Set start)
                this.fСписок = value;
                // *** Start programmer edit section *** (Сотрудники.Список Set end)

                // *** End programmer edit section *** (Сотрудники.Список Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотрудникиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиE", typeof(IIS.Generaciya_6.Сотрудники));
                }
            }
            
            /// <summary>
            /// "СотрудникиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиL", typeof(IIS.Generaciya_6.Сотрудники));
                }
            }
        }
    }
}
