//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Generaciya_6
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Список.
    /// </summary>
    // *** Start programmer edit section *** (Список CustomAttributes)

    // *** End programmer edit section *** (Список CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СписокE", new string[0])]
    [AssociatedDetailViewAttribute("СписокE", "Анкетирование", "АнкетированиеE", true, "", "Анкетирование", true, new string[] {
            ""})]
    [View("СписокL", new string[0])]
    public class Список : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Generaciya_6.DetailArrayOfАнкетирование fАнкетирование;
        
        // *** Start programmer edit section *** (Список CustomMembers)

        // *** End programmer edit section *** (Список CustomMembers)

        
        /// <summary>
        /// Список.
        /// </summary>
        // *** Start programmer edit section *** (Список.Анкетирование CustomAttributes)

        // *** End programmer edit section *** (Список.Анкетирование CustomAttributes)
        public virtual IIS.Generaciya_6.DetailArrayOfАнкетирование Анкетирование
        {
            get
            {
                // *** Start programmer edit section *** (Список.Анкетирование Get start)

                // *** End programmer edit section *** (Список.Анкетирование Get start)
                if ((this.fАнкетирование == null))
                {
                    this.fАнкетирование = new IIS.Generaciya_6.DetailArrayOfАнкетирование(this);
                }
                IIS.Generaciya_6.DetailArrayOfАнкетирование result = this.fАнкетирование;
                // *** Start programmer edit section *** (Список.Анкетирование Get end)

                // *** End programmer edit section *** (Список.Анкетирование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Список.Анкетирование Set start)

                // *** End programmer edit section *** (Список.Анкетирование Set start)
                this.fАнкетирование = value;
                // *** Start programmer edit section *** (Список.Анкетирование Set end)

                // *** End programmer edit section *** (Список.Анкетирование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СписокE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СписокE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СписокE", typeof(IIS.Generaciya_6.Список));
                }
            }
            
            /// <summary>
            /// "СписокL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СписокL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СписокL", typeof(IIS.Generaciya_6.Список));
                }
            }
        }
    }
}
